#!/bin/bash

my_pid=$$
echo "My process ID is $my_pid"

echo "Launching gazebo_nav.launch"
roslaunch urdf_gazebo_nav gazebo_nav.launch &
sleep 6s
pid="$pid $!"


echo "rviz"
rosrun rviz rviz -d `rospack find urdf_gazebo_nav`/urdf_gazebo_nav.rviz &


trap "echo Killing all processes.; kill -2 TERM $pid; exit" SIGINT SIGTERM


